jobs:
  build:
    name: CI PR ${{ matrix.nickname }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: adopt
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      env:
        DISABLE_SAMPLES: ${{ matrix.disable-samples }}
      name: Build
      run: ./gradlew build
    strategy:
      fail-fast: false
      matrix:
        include:
        - disable-samples: true
          java: 17
          nickname: linux jdk17
    timeout-minutes: 15
name: CI PRs
on:
  repository_dispatch:
    types: trigger-ga___ci-pr.yml
