jobs:
  build:
    name: CI Build ${{ matrix.nickname }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: adopt
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build
      run: ./gradlew build
    strategy:
      fail-fast: false
      matrix:
        include:
        - java: 17
          nickname: linux jdk17
  publish:
    if: github.repository_owner == 'spring-projects'
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      env:
        JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: 2.21.5
    - continue-on-error: true
      name: Configure JFrog Cli
      run: "jf rt gradlec \\\n  --use-wrapper \\\n  --uses-plugin \\\n  --deploy-ivy-desc=false\
        \ \\\n  --server-id-resolve repo.spring.io \\\n  --server-id-deploy repo.spring.io\
        \ \\\n  --repo-resolve snapshot \\\n  --repo-deploy snapshot\necho JFROG_CLI_BUILD_NAME=spring-shell-main\
        \ >> $GITHUB_ENV\necho JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV\n"
    - continue-on-error: true
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY
          }}
        GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD
          }}
        GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER
          }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
      name: Build and Publish
      run: 'jf rt gradle build distZip artifactoryPublish

        jf rt build-publish

        '
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
