jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        ref: docs-build
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.ref_type == 'branch'
      name: Dispatch (partial build)
      run: gh workflow run deploy-docs.yml -r $(git rev-parse --abbrev-ref HEAD) -f
        build-refname=${{ github.ref_name }}
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.ref_type == 'tag'
      name: Dispatch (full build)
      run: gh workflow run deploy-docs.yml -r $(git rev-parse --abbrev-ref HEAD)
name: Deploy Docs
on:
  repository_dispatch:
    types: trigger-ga___deploy-docs.yml
permissions:
  actions: write
