jobs:
  dispatch_e2e:
    if: github.repository_owner == 'spring-projects'
    name: Dispatch e2e
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      name: Dispatch
      run: gh workflow run e2e.yml -r ${{ matrix.branch }}
    strategy:
      matrix:
        branch:
        - main
        - 3.2.x
        - 3.1.x
name: Schedule e2e
on:
  repository_dispatch:
    types: trigger-ga___schedule-e2e.yml
permissions:
  actions: write
